
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Mar 09 18:31:59 CET 2026
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INCREMENT = 29;
  public static final int CONST = 5;
  public static final int ASTERISK = 45;
  public static final int SLASH = 46;
  public static final int NOT_EQUAL = 39;
  public static final int CASE = 27;
  public static final int GREATER = 40;
  public static final int LPAREN = 15;
  public static final int CONTINUE = 21;
  public static final int LESS = 42;
  public static final int FOR = 26;
  public static final int MINUS = 33;
  public static final int DECREMENT = 30;
  public static final int CHARACTER = 50;
  public static final int RPAREN = 16;
  public static final int SEMICOLON = 6;
  public static final int AND = 32;
  public static final int OR = 31;
  public static final int COMMA = 7;
  public static final int CLASS = 11;
  public static final int LESS_EQUAL = 43;
  public static final int QUESTION_MARK = 34;
  public static final int PLUS = 44;
  public static final int IF = 18;
  public static final int DOT = 36;
  public static final int BOOLEAN = 49;
  public static final int ABSTRACT = 14;
  public static final int EOF = 0;
  public static final int RETURN = 22;
  public static final int EQUAL = 8;
  public static final int GREATER_EQUAL = 41;
  public static final int NEW = 35;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int PERCENT = 47;
  public static final int NUMBER = 48;
  public static final int BREAK = 20;
  public static final int VOID = 17;
  public static final int SWITCH = 25;
  public static final int COLON = 28;
  public static final int LBRACE = 3;
  public static final int ELSE = 19;
  public static final int LSQUARE = 9;
  public static final int ENUM = 13;
  public static final int READ = 23;
  public static final int RSQUARE = 10;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 12;
  public static final int EQUAL_EQUAL = 38;
  public static final int LENGTH = 37;
  public static final int PRINT = 24;
  public static final int IDENTIFIER = 51;
}

