package rs.ac.bg.etf.pp1;

import java_cup.runtime.*;
import org.apache.log4j.*;

// import java.io.*;
import rs.ac.bg.etf.pp1.ast.*;


parser code {:
	
	boolean errorDetected = false;
	
	Logger log = Logger.getLogger(getClass());
   
   
    // slede redefinisani metodi za prijavu gresaka radi izmene teksta poruke
     
    public void report_fatal_error(String message, Object info) throws java.lang.Exception {
      done_parsing();
      report_error(message, info);
    }
  
    public void syntax_error(Symbol cur_token) {
        report_error("\nSintaksna greska", cur_token);
    }
  
    public void unrecovered_syntax_error(Symbol cur_token) throws java.lang.Exception {
        report_fatal_error("Fatalna greska, parsiranje se ne moze nastaviti", cur_token);
    }

    public void report_error(String message, Object info) {
    	errorDetected = true;
    	StringBuilder msg = new StringBuilder(message); 
    	if (info instanceof Symbol)
            msg.append (" na liniji ").append(((Symbol)info).left);
        log.error(msg.toString());
    }
    
    public void report_info(String message, Object info) {
    	StringBuilder msg = new StringBuilder(message); 
    	if (info instanceof Symbol)
            msg.append (" na liniji ").append(((Symbol)info).left);
        log.info(msg.toString());
    }
    
:}

scan with {:
	Symbol s = this.getScanner().next_token();
	if (s != null && s.value != null) 
		log.info(s.toString() + " " + s.value.toString());
	return s;
:}


terminal PROGRAM, LBRACE, RBRACE, CONST, SEMICOLON, COMMA, EQUAL, LSQUARE;
terminal RSQUARE, CLASS, EXTENDS, ENUM, ABSTRACT, LPAREN, RPAREN, VOID, /* Statement deo */IF, ELSE, BREAK, CONTINUE, RETURN, READ, PRINT;
terminal SWITCH, FOR, CASE, COLON, INCREMENT, DECREMENT, OR, AND, MINUS, QUESTION_MARK, NEW, DOT, LENGTH, EQUAL_EQUAL;
terminal NOT_EQUAL, GREATER, GREATER_EQUAL, LESS, LESS_EQUAL, PLUS, ASTERISK, SLASH, PERCENT;
terminal Integer NUMBER, BOOLEAN;
terminal Character CHARACTER;
terminal String IDENTIFIER;

nonterminal Prog Prog;
nonterminal ProgDeclList ProgDeclList;
nonterminal MethDeclList MethDeclList;
nonterminal ProgDeclPart ProgDeclPart;
nonterminal ConstDecl ConstDecl;
nonterminal VarDecl VarDecl;
nonterminal ClassDecl ClassDecl;
nonterminal EnumDecl EnumDecl;
nonterminal AbstractClassDecl AbstractClassDecl;
nonterminal ConstDeclList ConstDeclList;
nonterminal ConstDeclPart ConstDeclPart;
nonterminal ConstDeclType ConstDeclType;
nonterminal VarDeclList VarDeclList;
nonterminal VarDeclPart VarDeclPart;
nonterminal ListOfVarDeclarations ListOfVarDeclarations;
nonterminal EnumDeclList EnumDeclList;
nonterminal EnumDeclPart EnumDeclPart;
nonterminal AbstractClassList AbstractClassList;
nonterminal AbstractClassListPart AbstractClassListPart;
nonterminal MethodDecl MethodDecl;
nonterminal AbstractMethodDecl AbstractMethodDecl;
nonterminal FormalParameters FormalParameters; 
nonterminal FormPars FormPars;
nonterminal ListOfStatements ListOfStatements;
nonterminal Statement Statement;
nonterminal FormParsPart FormParsPart;
nonterminal /* Statement deo */ DesignatorStatement DesignatorStatement;
nonterminal NumberPrint NumberPrint;
nonterminal CaseList CaseList;
nonterminal CaseListPart CaseListPart;
nonterminal Assignop Assignop;
nonterminal ActPars ActPars;
nonterminal Relop Relop;
nonterminal Addop Addop;
nonterminal Mulop Mulop;
nonterminal ElseStatement ElseStatement;
nonterminal IfCondition IfCondition;
nonterminal GlobalVarDecl GlobalVarDecl;
nonterminal GlobalVarDeclList GlobalVarDeclList;
nonterminal GlobalVarDeclPart GlobalVarDeclPart;
nonterminal DesignatorStatementUpdate DesignatorStatementUpdate;
nonterminal ProgName ProgName;
nonterminal EnumDeclName EnumDeclName;
nonterminal rs.etf.pp1.symboltable.concepts.Struct Factor, FactorList, Term, TermList, ExprNoCond, Expr, AssignmentError;
nonterminal rs.etf.pp1.symboltable.concepts.Obj Designator, DesignatorArrayName, MethodTypeName;
nonterminal ForNonTerm ForNonTerm;
nonterminal SwitchNonTerm SwitchNonTerm;
nonterminal rs.etf.pp1.symboltable.concepts.Struct Condition, CondTerm, CondFact, ConditionalExpr, Type;
nonterminal ActParDummyBegin ActParDummyBegin;
nonterminal ActParList ActParList;
nonterminal ActPar ActPar;
nonterminal OrNonTerm OrNonTerm;
nonterminal ElseDummy ElseDummy;
nonterminal ForInit ForInit;
nonterminal ForCond ForCond;
nonterminal ForUpdate ForUpdate;
nonterminal ForFirstSemicolon ForFirstSemicolon;
nonterminal ForSecondSemicolon ForSecondSemicolon;
nonterminal ForRparen ForRparen;
nonterminal CaseDummy CaseDummy;
nonterminal NumberDummy NumberDummy;
nonterminal TernaryColon TernaryColon;
nonterminal rs.etf.pp1.symboltable.concepts.Obj LengthDummy;

precedence left ELSE;

Prog ::= (Program) PROGRAM ProgName:P1 ProgDeclList:P2 LBRACE MethDeclList:M3 RBRACE {: RESULT=new Program(P1, P2, M3); RESULT.setLine(P1left); :};

ProgName ::= (ProgName) IDENTIFIER:I1 {: RESULT=new ProgName(I1); RESULT.setLine(I1left); :};

ProgDeclList ::= (ProgDecls) ProgDeclList:P1 ProgDeclPart:P2 {: RESULT=new ProgDecls(P1, P2); RESULT.setLine(P1left); :} 
				|
				(NoProgDecls) {: RESULT=new NoProgDecls(); :} /* epsilon */
				;

ProgDeclPart ::= (ProgConstDeclaration) ConstDecl:C1 {: RESULT=new ProgConstDeclaration(C1); RESULT.setLine(C1left); :}
				|
				(ProgVarDeclaration) GlobalVarDecl:G1 {: RESULT=new ProgVarDeclaration(G1); RESULT.setLine(G1left); :}
				|
				(ProgClassDeclaration) ClassDecl:C1 {: RESULT=new ProgClassDeclaration(C1); RESULT.setLine(C1left); :}
				|
				(ProgEnumDeclaration) EnumDecl:E1 {: RESULT=new ProgEnumDeclaration(E1); RESULT.setLine(E1left); :}
				|
				(ProgAbstractClassDeclaration) AbstractClassDecl:A1 {: RESULT=new ProgAbstractClassDeclaration(A1); RESULT.setLine(A1left); :}
				;
				
ConstDecl ::= (ConstDecl) CONST Type:T1 ConstDeclList:C2 SEMICOLON {: RESULT=new ConstDecl(T1, C2); RESULT.setLine(T1left); :};

ConstDeclList ::= (ConstDeclarationList) ConstDeclList:C1 COMMA ConstDeclPart:C2 {: RESULT=new ConstDeclarationList(C1, C2); RESULT.setLine(C1left); :}
				|
				(ConstDeclarationPart) ConstDeclPart:C1 {: RESULT=new ConstDeclarationPart(C1); RESULT.setLine(C1left); :}
				;
				
ConstDeclPart ::= (ConstDeclPart) IDENTIFIER:I1 EQUAL ConstDeclType:C2 {: RESULT=new ConstDeclPart(I1, C2); RESULT.setLine(I1left); :};

ConstDeclType ::= (ConstDeclNum) NUMBER:N1 {: RESULT=new ConstDeclNum(N1); RESULT.setLine(N1left); :}
				|
				(ConstDeclChar) CHARACTER:C1 {: RESULT=new ConstDeclChar(C1); RESULT.setLine(C1left); :}
				|
				(ConstDeclBool) BOOLEAN:B1 {: RESULT=new ConstDeclBool(B1); RESULT.setLine(B1left); :}
				;
				
GlobalVarDecl ::= (GlobalVarDecl) Type:T1 GlobalVarDeclList:G2 SEMICOLON {: RESULT=new GlobalVarDecl(T1, G2); RESULT.setLine(T1left); :};

GlobalVarDeclList ::= (GlobalVarDeclarationList) GlobalVarDeclList:G1 COMMA GlobalVarDeclPart:G2 {: RESULT=new GlobalVarDeclarationList(G1, G2); RESULT.setLine(G1left); :}
				|
				(GlobalVarDeclarationPart) GlobalVarDeclPart:G1 {: RESULT=new GlobalVarDeclarationPart(G1); RESULT.setLine(G1left); :}
				;		

GlobalVarDeclPart ::= (GlobalVarDeclPartNoSquare) IDENTIFIER:I1 {: RESULT=new GlobalVarDeclPartNoSquare(I1); RESULT.setLine(I1left); :}
				|
				(GlobalVarDeclPartSquare) IDENTIFIER:I1 LSQUARE RSQUARE {: RESULT=new GlobalVarDeclPartSquare(I1); RESULT.setLine(I1left); :}
				|
				error:e
				{: parser.report_error("Error on the line: " + eleft + " Global variable declaration faulty!", null); :} {: RESULT=new GlobalVarDeclPartDerived1(); :}
				;

VarDecl ::= (VarDecl) Type:T1 VarDeclList:V2 SEMICOLON {: RESULT=new VarDecl(T1, V2); RESULT.setLine(T1left); :};

VarDeclList ::= (VarDeclarationList) VarDeclList:V1 COMMA VarDeclPart:V2 {: RESULT=new VarDeclarationList(V1, V2); RESULT.setLine(V1left); :}
				|
				(VarDeclarationPart) VarDeclPart:V1 {: RESULT=new VarDeclarationPart(V1); RESULT.setLine(V1left); :}
				;
				
VarDeclPart ::= (VarDeclPartNoSquare) IDENTIFIER:I1 {: RESULT=new VarDeclPartNoSquare(I1); RESULT.setLine(I1left); :}
				|
				(VarDeclPartSquare) IDENTIFIER:I1 LSQUARE RSQUARE {: RESULT=new VarDeclPartSquare(I1); RESULT.setLine(I1left); :}
				;
				
ClassDecl ::= (ClassDeclNoExtNoMeth) CLASS IDENTIFIER:I1 LBRACE ListOfVarDeclarations:L2 RBRACE {: RESULT=new ClassDeclNoExtNoMeth(I1, L2); RESULT.setLine(I1left); :}
				|
				(ClassDeclNoExtMeth) CLASS IDENTIFIER:I1 LBRACE ListOfVarDeclarations:L2 LBRACE MethDeclList:M3 RBRACE RBRACE {: RESULT=new ClassDeclNoExtMeth(I1, L2, M3); RESULT.setLine(I1left); :}
				|
				(ClassDeclExtNoMeth) CLASS IDENTIFIER:I1 EXTENDS Type:T2 LBRACE ListOfVarDeclarations:L3 RBRACE {: RESULT=new ClassDeclExtNoMeth(I1, T2, L3); RESULT.setLine(I1left); :}
				|
				(ClassDeclExtMeth) CLASS IDENTIFIER:I1 EXTENDS Type:T2 LBRACE ListOfVarDeclarations:L3 LBRACE MethDeclList:M4 RBRACE RBRACE {: RESULT=new ClassDeclExtMeth(I1, T2, L3, M4); RESULT.setLine(I1left); :}
				;
				
ListOfVarDeclarations ::= (ListOfVarDeclarationss) ListOfVarDeclarations:L1 VarDecl:V2 {: RESULT=new ListOfVarDeclarationss(L1, V2); RESULT.setLine(L1left); :}
				|
				(NoVarDeclaration) {: RESULT=new NoVarDeclaration(); :} /* epsilon */
				;
				
EnumDecl ::= (EnumDecl) ENUM EnumDeclName:E1 LBRACE EnumDeclList:E2 RBRACE {: RESULT=new EnumDecl(E1, E2); RESULT.setLine(E1left); :};

EnumDeclName ::= (EnumDeclName) IDENTIFIER:I1 {: RESULT=new EnumDeclName(I1); RESULT.setLine(I1left); :};

EnumDeclList ::= (EnumDeclListt) EnumDeclList:E1 COMMA EnumDeclPart:E2 {: RESULT=new EnumDeclListt(E1, E2); RESULT.setLine(E1left); :}
				|
				(EnumDeclarationPart) EnumDeclPart:E1 {: RESULT=new EnumDeclarationPart(E1); RESULT.setLine(E1left); :}
				;
				
EnumDeclPart ::= (EnumDeclPartNoEqual) IDENTIFIER:I1 {: RESULT=new EnumDeclPartNoEqual(I1); RESULT.setLine(I1left); :}
				|
				(EnumDeclPartEqual) IDENTIFIER:I1 EQUAL NUMBER:N2 {: RESULT=new EnumDeclPartEqual(I1, N2); RESULT.setLine(I1left); :}
				;
				
AbstractClassDecl ::= (AbstrClassDeclNoExtNoList) ABSTRACT CLASS IDENTIFIER:I1 LBRACE ListOfVarDeclarations:L2 RBRACE {: RESULT=new AbstrClassDeclNoExtNoList(I1, L2); RESULT.setLine(I1left); :}
				|
				(AbstrClassDeclNoExtList) ABSTRACT CLASS IDENTIFIER:I1 LBRACE ListOfVarDeclarations:L2 LBRACE AbstractClassList:A3 RBRACE RBRACE {: RESULT=new AbstrClassDeclNoExtList(I1, L2, A3); RESULT.setLine(I1left); :}
				|
				(AbstrClassDeclExtNoList) ABSTRACT CLASS IDENTIFIER:I1 EXTENDS Type:T2 LBRACE ListOfVarDeclarations:L3 RBRACE {: RESULT=new AbstrClassDeclExtNoList(I1, T2, L3); RESULT.setLine(I1left); :}
				|
				(AbstrClassDEclExtList) ABSTRACT CLASS IDENTIFIER:I1 EXTENDS Type:T2 LBRACE ListOfVarDeclarations:L3 LBRACE AbstractClassList:A4 RBRACE RBRACE {: RESULT=new AbstrClassDEclExtList(I1, T2, L3, A4); RESULT.setLine(I1left); :}
				;
				
AbstractClassList ::= (AbstractClassListt) AbstractClassList:A1 AbstractClassListPart:A2 {: RESULT=new AbstractClassListt(A1, A2); RESULT.setLine(A1left); :}
				|
				(NoAbstractClassListPart) {: RESULT=new NoAbstractClassListPart(); :} /* epsilon */
				;

AbstractClassListPart ::= (AbstrClassMethDecl) MethodDecl:M1 {: RESULT=new AbstrClassMethDecl(M1); RESULT.setLine(M1left); :}
				|
				(AbstrClassAbstrMethDecl) AbstractMethodDecl:A1 SEMICOLON {: RESULT=new AbstrClassAbstrMethDecl(A1); RESULT.setLine(A1left); :}
				;
				
AbstractMethodDecl ::= (AbstrMethodType) ABSTRACT Type:T1 IDENTIFIER:I2 LPAREN FormalParameters:F3 RPAREN {: RESULT=new AbstrMethodType(T1, I2, F3); RESULT.setLine(T1left); :}
				|
				(AbstrMethodVoid) ABSTRACT VOID IDENTIFIER:I1 LPAREN FormalParameters:F2 RPAREN {: RESULT=new AbstrMethodVoid(I1, F2); RESULT.setLine(I1left); :}
				;
				
FormalParameters ::= (FormalParameterss) FormPars:F1 {: RESULT=new FormalParameterss(F1); RESULT.setLine(F1left); :}
				|
				(NoFormalParameters) {: RESULT=new NoFormalParameters(); :} /* epsilon */
				;

MethDeclList ::= (MethDeclListt) MethDeclList:M1 MethodDecl:M2 {: RESULT=new MethDeclListt(M1, M2); RESULT.setLine(M1left); :}
				|
				(NoMethodDeclarations) {: RESULT=new NoMethodDeclarations(); :} /* epsilon */
				;
				
MethodDecl ::= (MethodDecl) MethodTypeName:M1 LPAREN FormalParameters:F2 RPAREN ListOfVarDeclarations:L3 LBRACE ListOfStatements:L4 RBRACE {: RESULT=new MethodDecl(M1, F2, L3, L4); RESULT.setLine(M1left); :};

MethodTypeName ::= (MethTypeName) Type:T1 IDENTIFIER:I2 {: RESULT=new MethTypeName(T1, I2); RESULT.setLine(T1left); :}
				|
				(MethVoidName) VOID IDENTIFIER:I1 {: RESULT=new MethVoidName(I1); RESULT.setLine(I1left); :};

ListOfStatements ::= (ListOfStatementss) ListOfStatements:L1 Statement:S2 {: RESULT=new ListOfStatementss(L1, S2); RESULT.setLine(L1left); :}
				|
				(NoStatements) {: RESULT=new NoStatements(); :} /* epsilon */
				;

FormPars ::= (FormParss) FormPars:F1 COMMA FormParsPart:F2 {: RESULT=new FormParss(F1, F2); RESULT.setLine(F1left); :}
				|
				(FormalParameterPart) FormParsPart:F1 {: RESULT=new FormalParameterPart(F1); RESULT.setLine(F1left); :}
				;

FormParsPart ::= (FormParsPartNoSquare) Type:T1 IDENTIFIER:I2 {: RESULT=new FormParsPartNoSquare(T1, I2); RESULT.setLine(T1left); :}
				|
				(FormParsPartSquare) Type:T1 IDENTIFIER:I2 LSQUARE RSQUARE {: RESULT=new FormParsPartSquare(T1, I2); RESULT.setLine(T1left); :}
				|
				error:e
				{: parser.report_error("Error on the line: " + eleft + " Faulty formal parameter declaration!", null); :} {: RESULT=new FormParsPartDerived1(); :}
				;
				
Type ::= (Type) IDENTIFIER:I1 {: RESULT=new Type(I1); RESULT.setLine(I1left); :};

Statement ::= (StatementDesignatedStmt) DesignatorStatement:D1 SEMICOLON {: RESULT=new StatementDesignatedStmt(D1); RESULT.setLine(D1left); :}
				|
				(StatementIfElse) IF LPAREN IfCondition:I1 RPAREN Statement:S2 ElseStatement:E3 {: RESULT=new StatementIfElse(I1, S2, E3); RESULT.setLine(I1left); :}
				|
				(StatementBreak) BREAK SEMICOLON {: RESULT=new StatementBreak(); :}
				|
				(StatementContinue) CONTINUE SEMICOLON {: RESULT=new StatementContinue(); :}
				|
				(StatementReturnNoExpr) RETURN SEMICOLON {: RESULT=new StatementReturnNoExpr(); :}
				|
				(StatementReturnExpr) RETURN Expr:E1 SEMICOLON {: RESULT=new StatementReturnExpr(E1); RESULT.setLine(E1left); :}
				|
				(StatementRead) READ LPAREN Designator:D1 RPAREN SEMICOLON {: RESULT=new StatementRead(D1); RESULT.setLine(D1left); :}
				|
				(StatementPrint) PRINT LPAREN Expr:E1 NumberPrint:N2 RPAREN SEMICOLON {: RESULT=new StatementPrint(E1, N2); RESULT.setLine(E1left); :}
				|
				(StatementSwitch) SwitchNonTerm:S1 LPAREN Expr:E2 RPAREN LBRACE CaseList:C3 RBRACE {: RESULT=new StatementSwitch(S1, E2, C3); RESULT.setLine(S1left); :}
				|
				(StatementFor) ForNonTerm:F1 LPAREN ForInit:F2 ForFirstSemicolon:F3 ForCond:F4 ForSecondSemicolon:F5 ForUpdate:F6 ForRparen:F7 Statement:S8 {: RESULT=new StatementFor(F1, F2, F3, F4, F5, F6, F7, S8); RESULT.setLine(F1left); :}
				|
				(StatementBlock) LBRACE ListOfStatements:L1 RBRACE {: RESULT=new StatementBlock(L1); RESULT.setLine(L1left); :}
				;
				
ForFirstSemicolon ::= (ForFirstSemicolon) SEMICOLON {: RESULT=new ForFirstSemicolon(); :};
				
ForSecondSemicolon ::= (ForSecondSemicolon) SEMICOLON {: RESULT=new ForSecondSemicolon(); :};

ForRparen ::= (ForRparen) RPAREN {: RESULT=new ForRparen(); :};
				
ForInit ::= (ForInitt) DesignatorStatement:D1 {: RESULT=new ForInitt(D1); RESULT.setLine(D1left); :}
				|
				(NoForInit) {: RESULT=new NoForInit(); :} /* epsilon */
				;

ForCond ::= (ForCondd) Condition:C1 {: RESULT=new ForCondd(C1); RESULT.setLine(C1left); :}
				|
				(NoForCond) {: RESULT=new NoForCond(); :} /* epsilon */
				;

ForUpdate ::= (ForUpdatee) DesignatorStatementUpdate:D1 {: RESULT=new ForUpdatee(D1); RESULT.setLine(D1left); :}
				|
				(NoForUpdate) {: RESULT=new NoForUpdate(); :} /* epsilon */
				;

ElseStatement ::= (ElseStmt) ElseDummy:E1 Statement:S2 {: RESULT=new ElseStmt(E1, S2); RESULT.setLine(E1left); :}
				|
				(NoElseStmt) {: RESULT=new NoElseStmt(); :} /* epsilon */
				;

ElseDummy ::= (ElseDummy) ELSE {: RESULT=new ElseDummy(); :};
				
ForNonTerm ::= (ForNonTerm) FOR {: RESULT=new ForNonTerm(); :};

SwitchNonTerm ::= (SwitchNonTerm) SWITCH {: RESULT=new SwitchNonTerm(); :};
				
IfCondition ::= (IfCond) Condition:C1 {: RESULT=new IfCond(C1); RESULT.setLine(C1left); :}
				|
				error:e
				{: parser.report_error("Error on the line: " + eleft + " Condition for if construction faulty!" , null); :} {: RESULT=new IfConditionDerived1(); :}
				;				
				
NumberPrint ::= (NumberPrintt) COMMA NUMBER:N1 {: RESULT=new NumberPrintt(N1); RESULT.setLine(N1left); :}
				|
				(NoNumberPrint) {: RESULT=new NoNumberPrint(); :} /* epsilon */
				;

CaseList ::= (CaseListt) CaseList:C1 CaseListPart:C2 {: RESULT=new CaseListt(C1, C2); RESULT.setLine(C1left); :}
				|
				(NoCaseList) {: RESULT=new NoCaseList(); :} /* epsilon */
				;
				
CaseListPart ::= (CaseListPart) CaseDummy:C1 NumberDummy:N2 COLON ListOfStatements:L3 {: RESULT=new CaseListPart(C1, N2, L3); RESULT.setLine(C1left); :};

CaseDummy ::= (CaseDummy) CASE {: RESULT=new CaseDummy(); :};

NumberDummy ::= (NumberDummy) NUMBER:N1 {: RESULT=new NumberDummy(N1); RESULT.setLine(N1left); :};

DesignatorStatement ::= (DesignatorStatementAssign) Designator:D1 Assignop:A2 AssignmentError:A3 {: RESULT=new DesignatorStatementAssign(D1, A2, A3); RESULT.setLine(D1left); :}
				|
				(DesignatorStatementNoActPars) Designator:D1 LPAREN RPAREN {: RESULT=new DesignatorStatementNoActPars(D1); RESULT.setLine(D1left); :}
				|
				(DesignatorStatementActPars) Designator:D1 LPAREN ActPars:A2 RPAREN {: RESULT=new DesignatorStatementActPars(D1, A2); RESULT.setLine(D1left); :}
				|
				(DesignatorStatementInc) Designator:D1 INCREMENT {: RESULT=new DesignatorStatementInc(D1); RESULT.setLine(D1left); :}
				|
				(DesignatorStatementDec) Designator:D1 DECREMENT {: RESULT=new DesignatorStatementDec(D1); RESULT.setLine(D1left); :}
				;
				
AssignmentError ::= (AssignNoError) Expr:E1 {: RESULT=new AssignNoError(E1); RESULT.setLine(E1left); :}
				|
				error:e
				{: parser.report_error("Error on the line: " + eleft + " Faulty assignment expression!", null); :} {: RESULT=new AssignmentErrorDerived1(); :}
				;							
				
DesignatorStatementUpdate ::= (DesignatorStatementAssignUpdate) Designator:D1 Assignop:A2 Expr:E3 {: RESULT=new DesignatorStatementAssignUpdate(D1, A2, E3); RESULT.setLine(D1left); :}
				|
				(DesignatorStatementNoActParsUpdate) Designator:D1 LPAREN RPAREN {: RESULT=new DesignatorStatementNoActParsUpdate(D1); RESULT.setLine(D1left); :}
				|
				(DesignatorStatementActParsUpdate) Designator:D1 LPAREN ActPars:A2 RPAREN {: RESULT=new DesignatorStatementActParsUpdate(D1, A2); RESULT.setLine(D1left); :}
				|
				(DesignatorStatementIncUpdate) Designator:D1 INCREMENT {: RESULT=new DesignatorStatementIncUpdate(D1); RESULT.setLine(D1left); :}
				|
				(DesignatorStatementDecUpdate) Designator:D1 DECREMENT {: RESULT=new DesignatorStatementDecUpdate(D1); RESULT.setLine(D1left); :}
				;				
				
ActPars ::= (ActPars) ActParDummyBegin:A1 ActPar:A2 ActParList:A3 {: RESULT=new ActPars(A1, A2, A3); RESULT.setLine(A1left); :};

ActParDummyBegin ::= (ActParDummyBegin) {: RESULT=new ActParDummyBegin(); :} /* epsilon */;

ActParList ::= (ActParListt) COMMA ActPar:A1 ActParList:A2 {: RESULT=new ActParListt(A1, A2); RESULT.setLine(A1left); :}
				|
				(ActParListEmpty) {: RESULT=new ActParListEmpty(); :} /* epsilon */
				;
				
ActPar ::= (ActPar) Expr:E1 {: RESULT=new ActPar(E1); RESULT.setLine(E1left); :};

Condition ::= (Conditionn) Condition:C1 OrNonTerm:O2 CondTerm:C3 {: RESULT=new Conditionn(C1, O2, C3); RESULT.setLine(C1left); :}
				|
				(ConditionCondTerm) CondTerm:C1 {: RESULT=new ConditionCondTerm(C1); RESULT.setLine(C1left); :}
				;
				
OrNonTerm ::= (OrNonTerm) OR {: RESULT=new OrNonTerm(); :};				
				
CondTerm ::= (CondTermm) CondTerm:C1 AND CondFact:C2 {: RESULT=new CondTermm(C1, C2); RESULT.setLine(C1left); :}
				|
				(CondTermCondFact) CondFact:C1 {: RESULT=new CondTermCondFact(C1); RESULT.setLine(C1left); :}
				;

CondFact ::= (CondFactt) ExprNoCond:E1 Relop:R2 ExprNoCond:E3 {: RESULT=new CondFactt(E1, R2, E3); RESULT.setLine(E1left); :}
				|
				(CondFactExpr) ExprNoCond:E1 {: RESULT=new CondFactExpr(E1); RESULT.setLine(E1left); :}
				;
				
Expr ::= (ExprCond) ConditionalExpr:C1 {: RESULT=new ExprCond(C1); RESULT.setLine(C1left); :}
				|
				(ExprNoConditional) ExprNoCond:E1 {: RESULT=new ExprNoConditional(E1); RESULT.setLine(E1left); :}
				;

ConditionalExpr ::= (ExprCondOr) Condition:C1 QUESTION_MARK Expr:E2 TernaryColon:T3 Expr:E4 {: RESULT=new ExprCondOr(C1, E2, T3, E4); RESULT.setLine(C1left); :};

TernaryColon ::= (TernaryColon) COLON {: RESULT=new TernaryColon(); :};

ExprNoCond ::= (ExprNoCond) TermList:T1 {: RESULT=new ExprNoCond(T1); RESULT.setLine(T1left); :};

TermList ::= (TermListt) TermList:T1 Addop:A2 Term:T3 {: RESULT=new TermListt(T1, A2, T3); RESULT.setLine(T1left); :}
				|
				(TermListPartNoMinus) Term:T1 {: RESULT=new TermListPartNoMinus(T1); RESULT.setLine(T1left); :}
				|
				(TermListPartMinus) MINUS Term:T1 {: RESULT=new TermListPartMinus(T1); RESULT.setLine(T1left); :}
				;

Term ::= (Term) FactorList:F1 {: RESULT=new Term(F1); RESULT.setLine(F1left); :};

FactorList ::= (FactorListt) FactorList:F1 Mulop:M2 Factor:F3 {: RESULT=new FactorListt(F1, M2, F3); RESULT.setLine(F1left); :}
				|
				(FactorListPart) Factor:F1 {: RESULT=new FactorListPart(F1); RESULT.setLine(F1left); :}
				;
				
Factor ::= (FactorVariableReference) Designator:D1 {: RESULT=new FactorVariableReference(D1); RESULT.setLine(D1left); :}
				|
				(FactorFunctionCallNoActPars) Designator:D1 LPAREN RPAREN {: RESULT=new FactorFunctionCallNoActPars(D1); RESULT.setLine(D1left); :}
				|
				(FactorFunctionCallActPars) Designator:D1 LPAREN ActPars:A2 RPAREN {: RESULT=new FactorFunctionCallActPars(D1, A2); RESULT.setLine(D1left); :}
				|
				(FactorNumber) NUMBER:N1 {: RESULT=new FactorNumber(N1); RESULT.setLine(N1left); :}
				|
				(FactorChar) CHARACTER:C1 {: RESULT=new FactorChar(C1); RESULT.setLine(C1left); :}
				|
				(FactorBool) BOOLEAN:B1 {: RESULT=new FactorBool(B1); RESULT.setLine(B1left); :}
				|
				(FactorNewNoExpr) NEW Type:T1 {: RESULT=new FactorNewNoExpr(T1); RESULT.setLine(T1left); :}
				|
				(FactorNewExpr) NEW Type:T1 LSQUARE Expr:E2 RSQUARE {: RESULT=new FactorNewExpr(T1, E2); RESULT.setLine(T1left); :}
				|
				(FactorParenthesis) LPAREN Expr:E1 RPAREN {: RESULT=new FactorParenthesis(E1); RESULT.setLine(E1left); :}
				;
				
Designator ::= (DesignatorVar) IDENTIFIER:I1 {: RESULT=new DesignatorVar(I1); RESULT.setLine(I1left); :}
				|
				(DesignatorEnum) IDENTIFIER:I1 DOT IDENTIFIER:I2 {: RESULT=new DesignatorEnum(I1, I2); RESULT.setLine(I1left); :}
				|
				(DesignatorLength) IDENTIFIER:I1 DOT LengthDummy:L2 {: RESULT=new DesignatorLength(I1, L2); RESULT.setLine(I1left); :}
				|
				(DesignatorArray) DesignatorArrayName:D1 LSQUARE Expr:E2 RSQUARE {: RESULT=new DesignatorArray(D1, E2); RESULT.setLine(D1left); :}
				;
				
LengthDummy ::= (LengthDummy) LENGTH {: RESULT=new LengthDummy(); :};
				
DesignatorArrayName ::= (DesignatorArrayName) IDENTIFIER:I1 {: RESULT=new DesignatorArrayName(I1); RESULT.setLine(I1left); :};				
				
Assignop ::= (Assignopp) EQUAL {: RESULT=new Assignopp(); :};

Relop ::= (RelopEqEq) EQUAL_EQUAL {: RESULT=new RelopEqEq(); :}
				|
				(RelopNotEq) NOT_EQUAL {: RESULT=new RelopNotEq(); :}
				|
				(RelopGr) GREATER {: RESULT=new RelopGr(); :}
				|
				(RelopGrEq) GREATER_EQUAL {: RESULT=new RelopGrEq(); :}
				|
				(RelopLe) LESS {: RESULT=new RelopLe(); :}
				|
				(RelopLeEq) LESS_EQUAL {: RESULT=new RelopLeEq(); :}
				;
				
Addop ::= (AddopPl) PLUS {: RESULT=new AddopPl(); :}
				|
				(AddopMi) MINUS {: RESULT=new AddopMi(); :}
				;
				
Mulop ::= (MulopAs) ASTERISK {: RESULT=new MulopAs(); :}
				|
				(MulopSl) SLASH {: RESULT=new MulopSl(); :}
				|
				(MulopPe) PERCENT {: RESULT=new MulopPe(); :}
				;